### ISSUE TITLE
Cosmos DB property "$type" is skipped when serializing to JSON

### ISSUE THREAD

**Issue by mywyb2** [AzureCosmosDB/data-migration-desktop-tool#127] opened 2024-04-17 20:50 UTC
My Cosmos DB NoSQL-container contains documents with a string property `$type` (possibly nested within the object), e.g. 
```
{
    "id": "fb9351ca-6459-4b03-af08-43c488cc748d",
    "foo": {
        "$type": "typeA",
        "bar": "baz"
    }
}
```
Exporting the container to a JSON file results in documents where `$type` is skipped:
```
{
    "id": "fb9351ca-6459-4b03-af08-43c488cc748d",
    "foo": {
        "bar": "baz"
    }
}
```

**Comment by bowencode** [comment] 2024-04-18 19:26
Duplicate of #97

**Closed** 2024-04-18 19:26 UTC
